on:
  push:
    branches: [ 1.7 ]
  pull_request:
    branches: [ 1.7 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Build with command Gradlew
        run: ./gradlew build
        
      - name: Upload JAR file
        uses: actions/upload-artifact@v3
        with:
          name: VeinMiner
          path: build/libs/*.jar
