name: Java CI with Gradle

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew SetupCIWorkspace build -PuseCommitHashInVersion
      - uses: actions/upload-artifact@v2
        with:
          name: VeinMiner-1.7.10
          path: build/libs
      - name: Discord notification
      - uses: fateyan/action-discord-notifier@v1.2.0
        with:
          message-title: New Commits Pushed
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
